import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

const TopBar: React.FunctionComponent = () => {
  return (
    <div className="sticky top-0 flex flex-row content-center justify-evenly items-stretch text-center w-full bg-slate-900">
      <Link className="basis-1/6 p-5 my-2" href="/">
        Home
      </Link>
      <Link className="basis-1/6 p-5 my-2" href="/projects">
        Projects
      </Link>
      <Link className="basis-1/6 p-5 my-2" href="/about">
        About
      </Link>
      <Link className="basis-1/6 p-5 my-2" href="/contacts">
        Contacts
      </Link>
    </div>
  )
}

export const metadata = {
  title: 'My Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopBar />
        {children}
      </body>
    </html>
  )
}
